### PR TITLE
git cherry-pick f2b79bdaf47332e8ee70bcf38f14be9b1258223

### PR DESCRIPTION
**Pull request by otaviojava**

### CODE REVIEW

**Comment by jgallimore** [comment]
Is there a release notes file in here to update? If not, can you copy it over from 1.7.x-TT.x-release?

**Comment by otaviojava** [comment]
Sure, I'll wait until this merge to do a cherry-pic: https://github.com/tomitribe/tomee/pull/62

**Comment by jgallimore** [comment]
That's now merged, can you pull that change over

**Comment by otaviojava** [comment]
Done

**Pull request closed without merging**
