### PR TITLE
[WIP] [Send-upsteam-to-OSS] Use fixed keystores instead of an Ant task to speed up build and make…

### PR DESCRIPTION
**Pull request by exabrial**
… it more determinisic

### CODE REVIEW

**Comment by exabrial** [comment]
retest this please

**Comment by exabrial** [comment]
retest this please

**Comment by jeanouii** [comment]
I believe the reason to not check them in was to avoid breaking the build because the certificate is no more valid and we forgot to change the keystore.

**Comment by jgallimore** [comment]
We'll look at that again. @exabrial thought there was some non-deterministic about these tests.

**Comment by tomitribe-dev** [comment]
don't mind just wanted to share the reason why it's been done this way.

--
Jean-Louis Monteiro
http://twitter.com/jlouismonteiro
http://www.tomitribe.com

**Comment by jgallimore** [comment]
I appreciate it. I think its worth another look at this failure. I've reverted it here in order to run the test again.

**Pull request merged**
